// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDoacao.MODEL.Models;

public partial class ADMINISTRADOR
{
    public int AdmCodigo { get; set; }

    public string AdmUsuario { get; set; }

    public string AdmSenha { get; set; }
}