// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace SistemaDoacao.MODEL.Models;

public partial class CATEGORIA
{
    public int CatCodigo { get; set; }

    public string CatNome { get; set; }

    public DateTime CatDataRegistro { get; set; }

    public virtual ICollection<LOCALIDADE> CLCodigoLocalidades { get; set; } = new List<LOCALIDADE>();
}